### PR TITLE
Us 06

### PR DESCRIPTION
**Pull request by nmbruce**

### CODE REVIEW

**Review by jtchaseASU — APPROVED** [review]
Code looks good, commented, and tagged with initials. Tested locally on my Pixel phone and it worked fine.

**Comment by nmbruce** [comment]
Incorrect build path in index.html. Closed.

**Comment by nmbruce** [comment]
Reverted build path. Ready for review again.

**Comment by dtmcdona** [comment]
I talked directly to nmbruce about the build path so now it looks correct.

**Pull request merged**
